package br.com.PortalRh.Projeto.model.enuns;

public enum TipoCargo {

    ASSISTENTEDEDESENVOLVIMENTO,
    ASSISTENTEFINANCEIRO,
    ASSISTENTEADMINISTRATIVO,
    ANALISTADEDESENVOLVIMENTO,
    ANALISTAFINANCEIRO,
    ANALISTAADMINISTRATIVO,
    GERENTEDEDESENVOLVIMENTO,
    GERENTEFINANCEIRO,
    GERENTEADMINISTRATIVO;
}
