package br.com.PortalRh.Projeto.entities.enums;

public enum JobType {

    ASSISTENTEDEDESENVOLVIMENTO,
    ASSISTENTEFINANCEIRO,
    ASSISTENTEADMINISTRATIVO,
    ANALISTADEDESENVOLVIMENTO,
    ANALISTAFINANCEIRO,
    ANALISTAADMINISTRATIVO,
    GERENTEDEDESENVOLVIMENTO,
    GERENTEFINANCEIRO,
    GERENTEADMINISTRATIVO;
}
